// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_ol8X6lViHFEeSGi6JF-UP6ogtdDIvCg',
    appId: '1:599974635834:web:38e5c34d6fe00d288d4803',
    messagingSenderId: '599974635834',
    projectId: 'fakir-chat',
    authDomain: 'fakir-chat.firebaseapp.com',
    storageBucket: 'fakir-chat.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCn0yXb9_lALhvuhguj4kQWMfRZPsg2SM',
    appId: '1:599974635834:android:1e0a8c9b90beeee28d4803',
    messagingSenderId: '599974635834',
    projectId: 'fakir-chat',
    storageBucket: 'fakir-chat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHaDifPm-WI2x_-rRirfZ-tSK-4oZ9tng',
    appId: '1:599974635834:ios:b85d92ece89b0b8c8d4803',
    messagingSenderId: '599974635834',
    projectId: 'fakir-chat',
    storageBucket: 'fakir-chat.appspot.com',
    iosBundleId: 'com.fakir.fakirchat.fakirChat',
  );
}
